# Generated by Django 2.2 on 2020-07-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(default='', max_length=20, verbose_name='тема'),
        ),
    ]
