# Generated by Django 2.2 on 2020-08-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200730_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default='2020-08-02 15:37:01', verbose_name='время')),
                ('text', models.TextField(max_length=1000, verbose_name='текст')),
                ('title', models.CharField(max_length=50, verbose_name='заголовок')),
                ('link', models.IntegerField(verbose_name='ссылка')),
                ('permission', models.BooleanField(default=False, verbose_name='разрешение')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='почта'),
        ),
    ]
