# Generated by Django 2.2 on 2020-08-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20200802_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.TextField(default='2020-08-02 15:55:43', verbose_name='время'),
        ),
    ]
