# Generated by Django 2.2 on 2020-08-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20200802_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='theme',
            field=models.CharField(default='', max_length=15, verbose_name='тема'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.TextField(default='2020-08-03 12:53:37', verbose_name='время'),
        ),
    ]
