# Generated by Django 2.2 on 2020-08-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200803_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.TextField(default='2020-08-04 10:38:19', verbose_name='время'),
        ),
        migrations.AlterField(
            model_name='news',
            name='theme',
            field=models.CharField(default='Политика Медицина Экономика Спорт Экология IT Авто Наука Культура', max_length=15, verbose_name='тема'),
        ),
    ]
